CREATE TABLE PRODUTOS (
  idProduto INTEGER PRIMARY KEY AUTOINCREMENT,
  categoria VARCHAR(50)
);

CREATE TABLE PRODUTOS_HAS_ESTOQUE(
    PRODUTOS idProduto INTEGER,
    ESTOQUE idEstoque INTEGER,
    quantidade INTEGER
);

CREATE TABLE disponibilizando_um_produto(
    FORNECEDOR idFornecedor INTEGER,
    PRODUTOS idProduto INTEGER
);

CREATE TABLE PRODUTOS_POR_VENDEDOR(
    TERCEIRO_VENDEDOR vendedor INTEGER,
    PRODUTOS idProduto INTEGER,
    local VARCHAR(50)
);


CREATE TABLE FORNECEDOR(
  idFornecedor INTEGER PRIMARY KEY AUTOINCREMENT,
  RazãoSocial VARCHAR(50),
  Cnpj VARCHAR(45)
);

CREATE TABLE ESTOQUE (
  idEstoque INTEGER PRIMARY KEY AUTOINCREMENT,
  localidade VARCHAR(50)
);

CREATE TABLE TERCEIRO_VENDEDOR (
  idTerceiro INTEGER PRIMARY KEY AUTOINCREMENT,
  razaoSocial VARCHAR(50),
  local varchar(50)
);

CREATE TABLE RELACAO_PRODUTO_PEDIDO (
    PRODUTOS idProduto INTEGER,
    PEDIDO idPedido INTEGER,
    quantidade INTEGER
    
);

CREATE TABLE PEDIDO (
  idPedido INTEGER PRIMARY KEY AUTOINCREMENT,
  statusPedido VARCHAR(50),
  descricao VARCHAR(50)
);

CREATE TABLE CLIENTES(
    IdClientes INTEGER PRIMARY KEY AUTOINCREMENT,
    nome VARCHAR(50),
    identificação VARCHAR(50),
    endereço VARCHAR(50)
)